import Exchange from './abstract/bluefin.js';
import type { Balances, Dict, Int, Market, Num, OHLCV, Order, OrderBook, OrderSide, OrderType, Position, Str, Strings, Ticker, Tickers, Trade, FundingRateHistory } from './base/types.js';
export default class bluefin extends Exchange {
    describe(): any;
    fetchMarkets(params?: {}): Promise<Market[]>;
    fetchTicker(symbol: string, params?: {}): Promise<Ticker>;
    fetchTickers(symbols?: Strings, params?: {}): Promise<Tickers>;
    fetchOrderBook(symbol: string, limit?: Int, params?: {}): Promise<OrderBook>;
    fetchTrades(symbol: string, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchOHLCV(symbol: string, timeframe?: string, since?: Int, limit?: Int, params?: {}): Promise<OHLCV[]>;
    fetchFundingRateHistory(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<FundingRateHistory[]>;
    fetchBalance(params?: {}): Promise<Balances>;
    fetchPositions(symbols?: Strings, params?: {}): Promise<Position[]>;
    fetchMyTrades(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Trade[]>;
    fetchOpenOrders(symbol?: Str, since?: Int, limit?: Int, params?: {}): Promise<Order[]>;
    createOrder(symbol: string, type: OrderType, side: OrderSide, amount: number, price?: Num, params?: {}): Promise<Order>;
    cancelOrder(id: string, symbol?: Str, params?: {}): Promise<Order>;
    cancelOrders(ids: string[], symbol?: Str, params?: {}): Promise<Order[]>;
    setLeverage(leverage: Int, symbol?: Str, params?: {}): Promise<any>;
    setMarginMode(marginMode: string, symbol?: Str, params?: {}): Promise<any>;
    addMargin(symbol: string, amount: number, params?: {}): Promise<any>;
    reduceMargin(symbol: string, amount: number, params?: {}): Promise<any>;
    withdraw(code: string, amount: number, address: string, tag?: Str, params?: {}): Promise<any>;
    parseMarket(market: Dict): Market;
    parseTicker(ticker: Dict, market?: Market): Ticker;
    parseTrade(trade: Dict, market?: Market): Trade;
    parseOrder(order: Dict, market?: Market): Order;
    parsePosition(position: Dict, market?: Market): Position;
    parseBalance(response: Dict): Balances;
    parseOHLCV(ohlcv: any, market?: Market): OHLCV;
    parseFundingRateHistory(entry: Dict, market?: Market): FundingRateHistory;
    parseOrderStatus(status: Str): string;
    parseOrderSide(side: Str): string;
    sign(path: string, api?: string, method?: string, params?: Dict, headers?: any, body?: any): Dict;
    authenticate(params?: {}): Promise<Dict>;
    refreshAccessToken(params?: {}): Promise<Dict>;
    getAccessToken(): Promise<string>;
    signRequest(fields: Dict): Dict;
    parseE9(value: string): number;
    toE9(value: number): string;
    convertE9Levels(levels: any[]): number[][];
    bluefinSymbol(ccxtSymbol: string): string;
    ccxtSymbol(bluefinSymbol: string): string;
}
